### ISSUE TITLE
Is the branch master production ready?

### ISSUE THREAD

**Issue by MauroSoli** [jitsi-contrib/jitsi-helm#102]
I need to use the `_interface_config_js` option, not supported in the `values.yaml` of the latest release 1.3.8.

Is the content of the current master branch production ready?

**Comment by spijet** [comment]
Hello @MauroSoli!

At the moment the `master` branch contains some new functionality from the recent PRs which I haven't personally tested yet. I'm planning to test it on my installation next week and, if all goes well, package a new release. In the meantime, you can try it on some sort of a staging setup (if you have one), unless you're feeling a bit adventurous. :)

**Comment by MauroSoli** [comment]
Thanks a lot!
