### ISSUE TITLE
Bad indentation for extra volumes

### ISSUE THREAD

**Issue by mathieusr** [jitsi-contrib/jitsi-helm#11]
Hello,

The **volumes** key in the web deployment isn't correctly indent:
https://github.com/jitsi-contrib/jitsi-helm/blob/df5a5fd62dfd0604bde2f6591c7041e426b6dae8/templates/web/deployment.yaml#L77-L80

Volumes shoud be part of spec.template.spec object 

I  can make a pull request if needed

Thanks

**Comment by sapkra** [comment]
Should be fixed with #10.
