### ISSUE TITLE
How to add/mount custom file in jitsi web pod ?

### ISSUE THREAD

**Issue by Govind10g** [jitsi-contrib/jitsi-helm#120]
Hi @spijet 

I have a requirement to mount a file in Jitsi Web pod, Can you help me how we can do that ?

![image](https://github.com/user-attachments/assets/fdc65041-1f54-47ad-bf51-c4296a2eb559)

**Comment by spijet** [comment]
Hello @Govind10g!

You can set a list of desired STUN/TURN servers in `values.yaml`:
https://github.com/jitsi-contrib/jitsi-helm/blob/main/values.yaml#L218

As for arbitrary custom configurations for Web service, you'll be able to do it once the 1.4.0 chart is released:
https://github.com/jitsi-contrib/jitsi-helm/blob/main/values.yaml#L60-L74

**Comment by spijet** [comment]
Chart v1.4.0 is up: https://github.com/jitsi-contrib/jitsi-helm/releases/tag/v1.4.0

Please consider upgrading and using the new features to customize your Web service configuration. I'm closing the issue for now, please reopen in case you have any issues.
