### ISSUE TITLE
Can we have a new release for chart version 1.4.0?

### ISSUE THREAD

**Issue by tibeer** [jitsi-contrib/jitsi-helm#121]
The chart is already at version 1.4.0, but the releases (and thus the helm index) are lacking the same. Can you create a new release, please? Thanks a lot :)

**Comment by spijet** [comment]
Hello @tibeer!

Thank you for the ping! I got caught up with work and totally forgot to re-test the 1.4.0 chart and release it. :D

**Comment by spijet** [comment]
Chart v1.4.0 is up! :D
https://github.com/jitsi-contrib/jitsi-helm/releases/tag/v1.4.0
