### ISSUE TITLE
Publish chart on artifacthub

### ISSUE THREAD

**Issue by varac** [jitsi-contrib/jitsi-helm#14]
[artifacthub](https://artifacthub.io) is the de-facto central catalog for helm charts, but I can't find this chart there: https://artifacthub.io/packages/search?ts_query_web=jitsi&sort=relevance&page=1

Please add it there for broader visibility, thanks !

**Comment by muckelba** [comment]
+1 for this. Artifacthub makes installing and updating so much easier with their "version comparing" and "values browsing" features. 

If you need help setting that up, feel free to reach out :)

**Comment by JuniorJPDJ** [comment]
very good idea ;)

**Comment by spijet** [comment]
Done, you can now find the chart and whatnot on ArtifactHub:
https://artifacthub.io/packages/helm/jitsi-meet/jitsi-meet
