### ISSUE TITLE
Release helm chart with Colibri Websockets support

### ISSUE THREAD

**Issue by ka11f** [jitsi-contrib/jitsi-helm#37]
This PR added support for Colibri websockets in K8s:
https://github.com/jitsi-contrib/jitsi-helm/pull/28

It seems that this feature is required for Jitsi to work in Chromium based browsers, and as such should be considered critical and released asap. However, it is still not released in the helm repo and that requires users to clone this repo instead of using the helm repo.

I would also like to thank everyone involved here for an otherwise great helm chart :)

**Comment by sapkra** [comment]
I did a release a few days ago which should include it.
