### ISSUE TITLE
Lots of info logs in browser per second

### ISSUE THREAD

**Issue by kseniyashaydurova** [jitsi-contrib/jitsi-helm#48]
Hi guys! We recently deployed the latest version of **jitsi-helm** chart (**1.2.2**). Everything looks fine from audio/video side, but we now see a strange behavior in browser - after upgrade there appears **100+ info logs in browser per second**. Is it ok? How we can reduce amount of info logs?

Below line is always repeated in logs:
`index.js:146 Halt: There are no SSRC groups in the remote description.`

Full logs file: 
[jitsi-contrib.vp.saritasa.rocks-1648003547829.log](https://github.com/jitsi-contrib/jitsi-helm/files/8329286/jitsi-contrib.vp.saritasa.rocks-1648003547829.log)

**Comment by kseniyashaydurova** [comment]
Hi again, finally we figured out that these huge logs appears when `websockets.enabled = false`. Turning on websockets solved it. But I'm not sure whether it is ok behavior or not within this helm chart. Maybe websockets should be always `turned on` by default as it was before?

**Comment by spijet** [comment]
Hello @kseniyashaydurova!

Thank you for your find! Up until recently, WebSockets were disabled by default in Jitsi Meet Docker images and weren't supported by this Helm chart at all. Right now I'm working on making it easier for everyone to use Jitsi Meet in either mode (with WebSockets or HTTP server polling) without any hidden surprises popping up here and there.

**Comment by spijet** [comment]
Should be fixed by cd3fa5efeb4658a276324d9f17da1f2df20a7305.
