### ISSUE TITLE
Noise canceling feature available?

### ISSUE THREAD

**Issue by sunkmou** [jitsi-contrib/jitsi-helm#57]
When we are using jitsi for meeting,there is huge background noise is huge where in we dont see that.Do we have any option or setting for noise cancellation?

**Comment by spijet** [comment]
Newer versions of Jitsi Meet have a "Noise Suppression" feature available in "three dots" menu (see attached screenshot). Maybe that's what you're looking for. I'm not sure about the exact version it was introduced in, but I have it in `stable-7648-4` version I use.
<img width="277" alt="image" src="https://user-images.githubusercontent.com/14221126/194134539-0171d52c-03d5-4848-a102-281cc0b939ca.png">

**Comment by spijet** [comment]
@sunkmou I'm closing the issue for now. Feel free to re-open if there are any problems with that feature.
