### ISSUE TITLE
how to configure the "org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS" about jvb

### ISSUE THREAD

**Issue by wujianqiangwjq** [jitsi-contrib/jitsi-helm#61]
how to configure the "org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS" about jvb

**Comment by spijet** [comment]
Hello @wujianqiangwjq!

You can use `.Values.jvb.publicIP` variable to set the public IP to be advertised by JVB:
```yaml
# values.yaml
jvb:
  publicIP: 1.2.3.4
```

Check the [JVB deployment template](https://github.com/jitsi-contrib/jitsi-helm/blob/main/templates/jvb/deployment.yaml#L60-L77) for details.

**Comment by wujianqiangwjq** [comment]
My meeting has been reconnecting. I think I need to configure "org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS", my environment does not STUN Server

**Comment by spijet** [comment]
That's exactly what the setting I mentioned does. Are you sure it's not caused by anything else? Can you describe your k8s setup? The problem may be hidden in Ingress or someplace else too.
