### ISSUE TITLE
how to set prejoinpageenable to false  in the jitsi web server

### ISSUE THREAD

**Issue by wujianqiangwjq** [jitsi-contrib/jitsi-helm#62]
how to set prejoinpageenable to false  in the jitsi web server

**Comment by spijet** [comment]
Hello @wujianqiangwjq!

You can change this setting (as well as many others) by providing custom environment variables to the `jitsi-meet-web` container, e.g. by using `.Values.web.extraEnvs`. You can find all options available for ENV-customization [in `docker-jitsi-meet` repo](https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/settings-config.js).
