### ISSUE TITLE
Implemented Jitsi using Helm charts but unable to autoscale Jitsi components.Kindly provide any documentation for Autoscaling?

### ISSUE THREAD

**Issue by sunkmou** [jitsi-contrib/jitsi-helm#65]

**Comment by spijet** [comment]
Hello @sunkmou!

Unfortunately, this chart doesn't feature any autoscaling templates as of now.
You'll have to implement Pod autoscaling yourself, but keep in mind that some components (e.g. Prosody and JVB) cannot be easily autoscaled, as they either are stateful or require different configs for different instances.

PRs are always welcome. :)
