### ISSUE TITLE
 Upgrade of jitsi using helm charts broke

### ISSUE THREAD

**Issue by rishu06** [jitsi-contrib/jitsi-helm#66]
Hi
I have upgrade my jitsi helm charts from version 1.2.2 to 1.3.2, I have followed all the changes that are in newer version like clusterdomain setting, websockets and jvb public ip
I see this error in prosody

speakerstats.meet.jitsi:speakerstats_component               error	No muc_component specified. No muc to operate on!
But jicofo and jvb are able to authenticate

2s55ee61b7faa0                                              info	Authenticated as jvb@auth.meet.jitsi
c2s55ee61ae2ce0                                              info	Client connected
c2s55ee61ae2ce0                                              info	Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
c2s55ee61ae2ce0                                              info	Authenticated as focus@auth.meet.jitsi
I dont see any error in jvb and jicofo logs

I am not able to start meeting
In console it says -
lib-jitsi-meet.min.js?v=6918:2 WebSocket connection to ‘wss://jitsi.xxxxxxxxxxxx’ failed:

<Object.getGlobalOnErrorHandler>: UnhandledError: Strophe: Websocket error [object Event] Script: null Line: null Column: null StackTrace: Error: Strophe: Websocket error [object Event]

I have enabled in websocket in values file

websockets:
    ## Colibri (JVB signalling):
    colibri:
      enabled: false
    ## XMPP (Prosody signalling):
    xmpp:
      enabled: true
Am i missing something or doing wrong ?
Thank you

**Comment by spijet** [comment]
Hello @rishu06!

Can you please describe your setup? Do you use HTTPS? Do you use any kind of Ingress controller, or maybe you just expose `jitsi/web` service via NodePort?

Using WebSockets nowadays requires properly-setup HTTPS. So if you don't have an HTTPS setup, it might be better to try installing this chart with both WebSocket options *disabled*, like this:
```
websockets:
  colibri:
    enabled: false
  xmpp:
    enabled: false
```

Other possible culprit might be your proxy, Ingress controller or some external proxy service — some of them don't work with WebSockets.

**Comment by rishu06** [comment]
Hi @spijet 
yes we use gke nginx-ingress-controller and use https.

**Comment by spijet** [comment]
I wrote a micro-guide on how to check if the websockets actually work in your Jitsi Meet installation in https://github.com/jitsi-contrib/jitsi-helm/discussions/64#discussioncomment-4907804. You can try checking if this shows any WSS activity in your case.
Also, please check if it works for you with WS support disabled — I found it working quite well in some setups.

**Comment by rishu06** [comment]
Hi @spijet 
<img width="507" alt="Screenshot 2023-04-13 at 11 07 04 AM" src="https://user-images.githubusercontent.com/15196600/231711761-4cf1ee4e-4d3d-4bda-a7f5-abdbc7c74780.png">
this is how response looks like for websocket

**Comment by spijet** [comment]
Hmm, I don't see any response code here (the window is too narrow, probably), which may mean that the client (app or browser) didn't receive any response at all. It should return an `HTTP 101 Switching Protocols` response and then switch to WebSocket mode. See screenshots below:
![image](https://user-images.githubusercontent.com/14221126/231857513-cb4d8468-a368-4ca6-8e03-16439833f155.png)
![image](https://user-images.githubusercontent.com/14221126/231858165-374638a0-40ef-4170-86b8-3d0a59ee4387.png)

**Comment by rishu06** [comment]
Hi 
It works now. 
Issue was this: `clusterDomain: ""`
Now I tried with 
`clusterDomain: cluster.local`

**Comment by spijet** [comment]
Good to know you've figured it out! `clusterDomain: cluster.local` is actually the global default in this chart, so probably something has overridden it in the process in your case.

Since it works now, I'll close the issue. Feel free to re-open or open a new one if need arises. :)
