### ISSUE TITLE
Add externalTrafficPolicy to jvb LoadBalancer service

### ISSUE THREAD

**Issue by mustdiechik** [jitsi-contrib/jitsi-helm#67]
https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec

"externalTrafficPolicy=Local" necessary to forward traffic directly to node on which jvb pod is located if used LoadBalancer.
In my case I get error like:
```
[confId=1e8ed2ae7bcce93a conf_name=capitalistcarrotsdesignatepoorly@muc.meet.jitsi meeting_id=e95b5a5c epId=25723256 stats_id=Nathanael-9Qo local_ufrag=egqph1gokqvqiq ufrag=egqph1gokqvqiq] ConnectivityCheckClient.processResponse#401: Received a non-symmetric response for pair: $IP1:10000/udp/srflx -> $IP2:29343/udp/prflx (stream-25723256.RTP). Failing.
```

**Comment by mustdiechik** [comment]
https://github.com/jitsi-contrib/jitsi-helm/pull/68

**Comment by spijet** [comment]
Thank you for your contribution, @mustdiechik!
I merged the PR and will pack a new release soon.

**Comment by spijet** [comment]
Hello @mustdiechik!

I just pushed a new release `v1.3.3`, which includes this fix.
