### ISSUE TITLE
error in README.md wrt jvb.publicIP?

### ISSUE THREAD

**Issue by jmozd** [jitsi-contrib/jitsi-helm#76]
In README.md, regarding different topologies and JVB configuration, "option 4" references a parameter jvb.publicIP.

Shouldn't that be "jvb.publicIPs", being a list, like in options 1 and 2?

I could find no reference to "jvb.publicIP" in the templates...

**Comment by spijet** [comment]
Actually, yes — the behavior was changed in chart version 1.3.1. I'll update the `README.md` tomorrow. Thank you for noticing!
