### ISSUE TITLE
How can I configure JVB which is running on Linux server with Jitsi Kubernetes deployment ?

### ISSUE THREAD

**Issue by Govind10g** [jitsi-contrib/jitsi-helm#81]
Hi All,

As this helm chart deploy Jitsi meet on Kubernetes cluster and as our Kubernetes cluster is in Private subnet and it is hard to auto scale JVB in kubernetes cluster hence we want to run only Jicofo, Prosody and web in kubernetes cluster and JVB on another linux server.

How we can make the changes in Jicofo i.e. JMS to communicate with JVB ?
Please help me how we can achieve this ? @spijet

**Comment by spijet** [comment]
Hello @Govind10g!

You want to deploy this chart without the JVB and instead run a set of JVBs separately from the k8s environment, right? In that case you might try to deploy this chart with the JVB service disabled and the number of JVB replicas set to `0`.
