### ISSUE TITLE
Is it possible to auto scale JMS pods ( web, prosody and jicofo) using Horizontal pod autoscaling ??

### ISSUE THREAD

**Issue by Govind10g** [jitsi-contrib/jitsi-helm#89]
Hi Team,

Wanted to understand, Is it possible to auto scale jitsi kubernetes pods i.e. WEB, JICOFO and PROSODY ??

In my architecture, I have a load balancer in front Kubernetes cluster to access the Jitsi UI application.
And JVB is running on EC2 server not in the kubernetes cluster and for JVB we are running multiple server to handle the load.
But for JMS (WEB, PROSODY and JICOFO) I don't know How we can auto scale ?? Or Is it possible or not ??

Please help me.

@saghul   @spijet

**Comment by spijet** [comment]
Hello @Govind10g!

It might be possible to implement the Horizontal Pod Autoscaling for the `web` component: it's stateless, so it should be relatively safe to scale it arbitrarily. I'm not sure about Jicofo, but Prosody is a stateful service that has to keep track of all the active user sessions and capabilities, so it might be much harder to implement autoscaling for it.

Do you have any specific issues with either of those components, which results in high utilization for them? How many rooms/users do you usually have accessing your Jitsi Meet installation?

**Comment by spijet** [comment]
I'm going to close this issue in favour of #111, because it's used to track the region sharding feature. If you have any additional information — feel free to post it here or there.
