### ISSUE TITLE
From where the prosody service url defined in jitsi-web  components ??

### ISSUE THREAD

**Issue by Govind10g** [jitsi-contrib/jitsi-helm#97]
Hi Team,
We are seeing error in the jitsi web pod when click on Join meeting.
the prosody url which formed in Jitsi web is not correct so we wanted to know from where it is picking up prosody url in Web ??

Any hint ??

**Comment by anirbandas18** [comment]
look into the config.js of jitsi meet web component

**Comment by spijet** [comment]
Hello @Govind10g!

Sorry for the late reply. All the internal URLs are handled by the ConfigMaps and/or some internal magic implemented in the Jitsi Meet Docker images. Please reopen the issue and let me know if you still have a problem with Prosody.
